spring:
  application:
    name: rest-core


  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:app_db}
    username: ${POSTGRES_USER_NAME:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: ${POSTGRES_DRIVER:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:none}
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: ${JPA_FORMAT_SQL:true}
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}



