spring.application.name=rest-core




spring.datasource.url=jdbc:postgresql://5.188.23.30:5050/app_db
spring.datasource.username=app_user
spring.datasource.password=AppDev_9kQm2nR4xL7p
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.ai.openai.enabled=false

